site_name: Affective Reality
repo_url: https://github.com/hnguyen25/affective-reality
theme:
  name: material

nav:
  - Introduction: 'index.md'
  - Getting Started: 'getting-started.md'
  - Overview and Progress:
    - Emotion Classification: 'emotion-classification.md'
    - Emotion Experiments: 'emotion-experiments.md'
    - Real-Time Application: 'vr-app.md'
  - User API:
    - Data Collection:
        - Stimulus Chooser: 'stimulus-chooser.md'
        - Experiment Runner: 'experiment-runner.md'
        - Data Collector: 'data-collector.md'
        - Data Saver: 'data-saver.md'
    - Data Analysis and Modelling:
        - Data: 'data.md'
        - Features: 'features.md'
        - Visualization: 'viz.md'
        - Models: 'models.md'
        - Deployment: 'deployment.md'
    - Real-Time Application and Deployment:
        - Sample Project -- Embodied Swarm: "embodied-swarm.md"

plugins:
  - search
  - mkdocstrings
